<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE pluginRecords [
<!ELEMENT pluginRecords ((update-site | disabled-update-site)*, plugin*)>
<!ELEMENT update-site EMPTY>
<!ELEMENT disabled-update-site EMPTY>
<!ELEMENT plugin (platform*, category*, version?, previous-version*)>
<!ELEMENT version (description?, dependency*, link*, author*)>
<!ELEMENT previous-version EMPTY>
<!ELEMENT description (#PCDATA)>
<!ELEMENT dependency EMPTY>
<!ELEMENT link (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST update-site name CDATA #REQUIRED>
<!ATTLIST update-site url CDATA #REQUIRED>
<!ATTLIST update-site keep-url CDATA #IMPLIED>
<!ATTLIST update-site official CDATA #IMPLIED>
<!ATTLIST update-site ssh-host CDATA #IMPLIED>
<!ATTLIST update-site upload-directory CDATA #IMPLIED>
<!ATTLIST update-site description CDATA #IMPLIED>
<!ATTLIST update-site maintainer CDATA #IMPLIED>
<!ATTLIST update-site timestamp CDATA #REQUIRED>
<!ATTLIST disabled-update-site name CDATA #REQUIRED>
<!ATTLIST disabled-update-site url CDATA #REQUIRED>
<!ATTLIST disabled-update-site keep-url CDATA #IMPLIED>
<!ATTLIST disabled-update-site official CDATA #IMPLIED>
<!ATTLIST disabled-update-site ssh-host CDATA #IMPLIED>
<!ATTLIST disabled-update-site upload-directory CDATA #IMPLIED>
<!ATTLIST disabled-update-site description CDATA #IMPLIED>
<!ATTLIST disabled-update-site maintainer CDATA #IMPLIED>
<!ATTLIST disabled-update-site timestamp CDATA #REQUIRED>
<!ATTLIST plugin update-site CDATA #IMPLIED>
<!ATTLIST plugin filename CDATA #REQUIRED>
<!ATTLIST plugin executable CDATA #IMPLIED>
<!ATTLIST dependency filename CDATA #REQUIRED>
<!ATTLIST dependency timestamp CDATA #IMPLIED>
<!ATTLIST dependency overrides CDATA #IMPLIED>
<!ATTLIST version timestamp CDATA #REQUIRED>
<!ATTLIST version checksum CDATA #REQUIRED>
<!ATTLIST version filesize CDATA #REQUIRED>
<!ATTLIST previous-version filename CDATA #IMPLIED>
<!ATTLIST previous-version timestamp CDATA #REQUIRED>
<!ATTLIST previous-version timestamp-obsolete CDATA #IMPLIED>
<!ATTLIST previous-version checksum CDATA #REQUIRED>]>
<pluginRecords>
    <plugin filename="jars/imglib2-5.8.0.jar">
        <previous-version timestamp="20120802184342" timestamp-obsolete="0" checksum="93b8dce33d5056707c27af51e21418a903d87049" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20120807204836" timestamp-obsolete="0" checksum="31abcd78f0ddc2e04ca73e9ad4ae699e5793f842" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20120817173023" timestamp-obsolete="0" checksum="78d3182d453ab0c620f6655aabe601c9c33b138f" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20120831192603" timestamp-obsolete="0" checksum="22f4b5b071f47372cdab9778415ab18bf918a6c5" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20120905181330" timestamp-obsolete="0" checksum="af8e104ce6a1999ef60243b91d6acfdd9d875ec0" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20120912153445" timestamp-obsolete="0" checksum="f3ae4f04811090142b43bbdc81aae2556b98808c" filename="jars/imglib2-2.0.0-beta4.jar"/>
        <previous-version timestamp="20121020192927" timestamp-obsolete="0" checksum="b71a6fad8d5303f63dd05beb751bc3b4617af6ec" filename="jars/imglib2-2.0.0-beta5.jar"/>
        <previous-version timestamp="20121106220203" timestamp-obsolete="0" checksum="0f9514030b32fe9e2b372538d6b1765b8ea48f87" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20121211213913" timestamp-obsolete="0" checksum="4fb6100461ed30e9b787b002ab2a0a8b72c8b415" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20130411222556" timestamp-obsolete="0" checksum="b37e58a79c3abae9d9f086b4eadce893699c249e" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20130501224547" timestamp-obsolete="0" checksum="7ee5c009d5e355cbbb91b7e419cbc24b1a1f1235" filename="jars/imglib2-2.0.0-SNAPSHOT.jar"/>
        <previous-version timestamp="20130620192406" timestamp-obsolete="0" checksum="1ee97bd0d10cba9bde8cf4d7cec2fa9fea0d4b2e" filename="jars/imglib2-2.0.0-beta-7.jar"/>
        <previous-version timestamp="20130716162630" timestamp-obsolete="0" checksum="1941524d418b9919be462adcf833aba6112aa2fb" filename="jars/imglib2-2.0.0-beta-9.jar"/>
        <previous-version timestamp="20130910183107" timestamp-obsolete="0" checksum="2197aa2ea27f071823f2f9d7fd46d84a59081041" filename="jars/imglib2-2.0.0-beta-15.jar"/>
        <previous-version timestamp="20131018164809" timestamp-obsolete="0" checksum="02ea6427711175455c40ced9a667bfbca3174cd5" filename="jars/imglib2-2.0.0-beta-20.jar"/>
        <previous-version timestamp="20131230181631" timestamp-obsolete="0" checksum="a24f6a79472458e645c6f5b7e7d9d572929162f9" filename="jars/imglib2-2.0.0-beta-22.jar"/>
        <previous-version timestamp="20140217152409" timestamp-obsolete="0" checksum="e06ba8d2285d47aa6c004e94e10e69e7958ba06c" filename="jars/imglib2-2.0.0-beta-24.jar"/>
        <previous-version timestamp="20140516211031" timestamp-obsolete="0" checksum="6e22d9dd33ce1c5ced83176fb0b88164fb0b409d" filename="jars/imglib2-2.0.0-beta-26.jar"/>
        <previous-version timestamp="20141219193933" timestamp-obsolete="0" checksum="225b3943f95efd287c43a751b3003c178065ba8a" filename="jars/imglib2-2.2.0.jar"/>
        <previous-version timestamp="20150318201525" timestamp-obsolete="0" checksum="d5f0909f2e53fdbe4f26d3c30d96d5bb5d202807" filename="jars/imglib2-2.2.1.jar"/>
        <previous-version timestamp="20150617164216" timestamp-obsolete="0" checksum="8f38c671571ada0ba7445f319f60aa7df5c51ce0" filename="jars/imglib2-2.3.0.jar"/>
        <previous-version timestamp="20150825195214" timestamp-obsolete="0" checksum="2b12ee6e3067da2770d3d7c288f61bcebcc4164b" filename="jars/imglib2-2.4.0.jar"/>
        <previous-version timestamp="20151122015629" timestamp-obsolete="0" checksum="28450b02f21d6235e6c1f2ef25fe4d6d47f38fe4" filename="jars/imglib2-2.4.1.jar"/>
        <previous-version timestamp="20151222021554" timestamp-obsolete="0" checksum="086a581dd89a6005d9ded43f1e9805de4db42b69" filename="jars/imglib2-2.5.0.jar"/>
        <previous-version timestamp="20160226143219" timestamp-obsolete="0" checksum="b2a26a3cfbfad4625529d8074f3e76b87af9912a" filename="jars/imglib2-2.6.0.jar"/>
        <previous-version timestamp="20160408145209" timestamp-obsolete="0" checksum="fc6440306f147622b9d6c249427f145d40d0012a" filename="jars/imglib2-2.7.0.jar"/>
        <previous-version timestamp="20160506160615" timestamp-obsolete="0" checksum="45ac8173b6b92b554802f55b5d7089f0a38dfe9c" filename="jars/imglib2-2.9.0.jar"/>
        <previous-version timestamp="20160818184259" timestamp-obsolete="0" checksum="b6547866a5b43dc5d7f5c409e72e35f17dae7d83" filename="jars/imglib2-3.2.0.jar"/>
        <previous-version timestamp="20170130141012" timestamp-obsolete="0" checksum="e2f0716dbaf8a7f357a3b55414114aab0a1b29ea" filename="jars/imglib2-3.2.1.jar"/>
        <previous-version timestamp="20170530201750" timestamp-obsolete="0" checksum="8119916b7935a5af873092dbba74f6f1188d743c" filename="jars/imglib2-4.2.1.jar"/>
        <previous-version timestamp="20171226155229" timestamp-obsolete="0" checksum="947c0a14bc8a58c71e504880a96649de5ac315d6" filename="jars/imglib2-4.6.0.jar"/>
        <previous-version timestamp="20180125120140" timestamp-obsolete="0" checksum="4ec423564ee6f5d1c780a77a736190bcf7def149" filename="jars/imglib2-4.6.1.jar"/>
        <previous-version timestamp="20180526000053" timestamp-obsolete="0" checksum="5f9856897e8b9ce9c73b30215758b35bcf9c9616" filename="jars/imglib2-5.2.0.jar"/>
        <previous-version timestamp="20180604210841" timestamp-obsolete="20181204141527" checksum="87fee9aa0e016d6aa1a4782ad533ab191e185824" filename="jars/imglib2-5.3.0.jar"/>
        <previous-version timestamp="20181204141527" timestamp-obsolete="20200607222322" checksum="09423bb02161e6396c0e792f26f43e17e6a13252" filename="jars/imglib2-5.6.3.jar"/>
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="08a866a4b23c330236af32df09247f7f7532faaa" filename="jars/imglib2-5.8.0.jar"/>
    </plugin>
    <plugin filename="jars/bigdataviewer-core-10.2.1.jar">
        <previous-version timestamp="20141219135141" timestamp-obsolete="0" checksum="df6a432d04f20781026c4f17b5d4615c4404af45" filename="jars/bigdataviewer-core-1.0.0.jar"/>
        <previous-version timestamp="20150213230609" timestamp-obsolete="0" checksum="1d36e571fbba4cc1780755f60f1fb7d64e96efbe" filename="jars/bigdataviewer-core-1.0.5.jar"/>
        <previous-version timestamp="20150216223535" timestamp-obsolete="0" checksum="4b8bbbbc974dda01fb2542046293c289890fac3a" filename="jars/bigdataviewer-core-1.0.6.jar"/>
        <previous-version timestamp="20150407220452" timestamp-obsolete="0" checksum="8cdca733516091e2cd2dc3941aa8d342e35b128f" filename="jars/bigdataviewer-core-1.0.8.jar"/>
        <previous-version timestamp="20150416130025" timestamp-obsolete="0" checksum="9cc9ef6e8ae43586c912640b71396cf75768543f" filename="jars/bigdataviewer-core-1.1.1.jar"/>
        <previous-version timestamp="20150417213935" timestamp-obsolete="0" checksum="eddf35b43d091ea49e390aaf3cd0aa058e3a5cb0" filename="jars/bigdataviewer-core-1.1.2.jar"/>
        <previous-version timestamp="20150430115943" timestamp-obsolete="0" checksum="2d62938a847fcfe29d81ff13b8e1078e5beafa08" filename="jars/bigdataviewer-core-1.1.3.jar"/>
        <previous-version timestamp="20150519235833" timestamp-obsolete="0" checksum="656507b3ca095edd6a55846af81e4096e8922972" filename="jars/bigdataviewer-core-1.1.4.jar"/>
        <previous-version timestamp="20150601174044" timestamp-obsolete="0" checksum="c35965b452fdfe4951976bacf6212f3cdb4b6ce3" filename="jars/bigdataviewer-core-1.2.0.jar"/>
        <previous-version timestamp="20150702135243" timestamp-obsolete="0" checksum="970f9d47652fff8f21308d3ff0ee4f9ac016eb0a" filename="jars/bigdataviewer-core-1.2.1.jar"/>
        <previous-version timestamp="20150723181610" timestamp-obsolete="0" checksum="d294eed6d49f9a6b37d3df7e8b25b596f4734192" filename="jars/bigdataviewer-core-1.2.2.jar"/>
        <previous-version timestamp="20151016212837" timestamp-obsolete="0" checksum="bcb6b042e06c1ec71b4b82a884f2fa6e26edad89" filename="jars/bigdataviewer-core-2.0.0.jar"/>
        <previous-version timestamp="20151027115445" timestamp-obsolete="0" checksum="96f89b8569e9db0d18b7b74c3c3c8643f829223b" filename="jars/bigdataviewer-core-2.0.1.jar"/>
        <previous-version timestamp="20151124135730" timestamp-obsolete="0" checksum="b5af7827c785b19f9ce221b6d9a35c7f4a23e8b5" filename="jars/bigdataviewer-core-2.1.0.jar"/>
        <previous-version timestamp="20160318125852" timestamp-obsolete="0" checksum="fee32c6c3172baf181ac00a2a651ebaf1c69a110" filename="jars/bigdataviewer-core-2.2.0.jar"/>
        <previous-version timestamp="20160318142130" timestamp-obsolete="0" checksum="3155f3a119fc21296886e95f446624c4be3888d9" filename="jars/bigdataviewer-core-2.2.1.jar"/>
        <previous-version timestamp="20160516123754" timestamp-obsolete="0" checksum="9be7b5798f2fe2ebd2cf3b0318903da21a437e58" filename="jars/bigdataviewer-core-2.4.0.jar"/>
        <previous-version timestamp="20160818184259" timestamp-obsolete="0" checksum="46366b02318c42f649698e19df873cbb4804112b" filename="jars/bigdataviewer-core-2.5.1.jar"/>
        <previous-version timestamp="20161114180218" timestamp-obsolete="0" checksum="9b6a58b56facde9e87d6968b22bd9575013dfb85" filename="jars/bigdataviewer-core-3.0.2.jar"/>
        <previous-version timestamp="20161116145920" timestamp-obsolete="0" checksum="3617303ba60e5036bc6c26091a762ac406b21f6a" filename="jars/bigdataviewer-core-3.0.2.jar"/>
        <previous-version timestamp="20161117001809" timestamp-obsolete="0" checksum="7bd5e539af3235025b06a69a0ab041dcfdadc83f" filename="jars/bigdataviewer-core-3.0.3.jar"/>
        <previous-version timestamp="20170530201750" timestamp-obsolete="0" checksum="2fb7f81b90dd7988fabf011da7d79f03b3d5122d" filename="jars/bigdataviewer-core-4.1.0.jar"/>
        <previous-version timestamp="20171226155229" timestamp-obsolete="0" checksum="638eb286883e66875ee0366a39e9960b4d12363d" filename="jars/bigdataviewer-core-4.3.1.jar"/>
        <previous-version timestamp="20180526000053" timestamp-obsolete="0" checksum="1da3ec5a93e64d55d573420854d148e71080be0f" filename="jars/bigdataviewer-core-5.0.0.jar"/>
        <previous-version timestamp="20181113140709" timestamp-obsolete="20190620123501" checksum="c42af02bea74ed95b4a055e47a15f5b1c8bb50ef" filename="jars/bigdataviewer-core-5.1.0.jar"/>
        <previous-version timestamp="20190620123458" timestamp-obsolete="20200731193402" checksum="09b0f2733846564c23705003c00aa1fd86652d01" filename="jars/bigdataviewer-core-7.0.0.jar"/>
        <previous-version timestamp="20200731193402" timestamp-obsolete="20200805001019" checksum="1cfcaa2ffbcc6c3ed90f5a3b22a389d3bf8e0b0e" filename="jars/bigdataviewer-core-9.0.5.jar"/>
        <previous-version timestamp="20200805001019" timestamp-obsolete="20210222164220" checksum="75b365f5a5c719cc104a5fb48434b5ca7b57b3e5" filename="jars/bigdataviewer-core-9.0.6.jar"/>
        <previous-version timestamp="20210222164216" timestamp-obsolete="20211112135002" checksum="3e0955f46e636062debaf64a6807556b82ec33c4" filename="jars/bigdataviewer-core-10.2.0.jar"/>
        <previous-version timestamp="20211112135001" timestamp-obsolete="20220927132817" checksum="54f34385f09f3ed9e65be6be62485aa40539fa12" filename="jars/bigdataviewer-core-10.2.1.jar"/>
    </plugin>
    <plugin filename="jars/spim_data-2.2.5.jar">
        <previous-version timestamp="20141219135141" timestamp-obsolete="0" checksum="1196743de146fb2bb5882ddd373537dcf991a856" filename="jars/spim_data-1.0.0-beta-3.jar"/>
        <previous-version timestamp="20150213230609" timestamp-obsolete="0" checksum="390943c5f99d4d78fa77c107d4c409319ad1767a" filename="jars/spim_data-1.0.0-beta-5.jar"/>
        <previous-version timestamp="20150417213935" timestamp-obsolete="0" checksum="3d8d1fca81d3630078c1110bac25041eac897c3b" filename="jars/spim_data-1.0.0-beta-7.jar"/>
        <previous-version timestamp="20151016212837" timestamp-obsolete="0" checksum="8d8518ea82d4b7c85e1febb299db8fa9ce2a1009" filename="jars/spim_data-2.0.0.jar"/>
        <previous-version timestamp="20151221214152" timestamp-obsolete="0" checksum="d45ac987d73eefb2c144f887a7ae808d9baf0b96" filename="jars/spim_data-2.0.1.jar"/>
        <previous-version timestamp="20160818184259" timestamp-obsolete="0" checksum="329f34eaf2b5fbb2fc2dfbc72491f616c1b1c3b9" filename="jars/spim_data-2.1.0.jar"/>
        <previous-version timestamp="20161114180218" timestamp-obsolete="0" checksum="8a53a66bd6e68273a1acb6c6add4930a768faa7a" filename="jars/spim_data-2.2.0.jar"/>
        <previous-version timestamp="20171124113040" timestamp-obsolete="0" checksum="528842d82403d0bfa3051a086212fd27b140c66c" filename="jars/spim_data-2.2.1.jar"/>
        <previous-version timestamp="20180806201151" timestamp-obsolete="20200731193402" checksum="f4781c7c20fb0e975e4a25741b488b953121ab0b" filename="jars/spim_data-2.2.2.jar"/>
        <previous-version timestamp="20200731193402" timestamp-obsolete="20211112135002" checksum="8b71c4e3d00961b0da1b7fbc06703fbf30bc7f9f" filename="jars/spim_data-2.2.5.jar"/>
        <previous-version timestamp="20211112135001" timestamp-obsolete="20220927132817" checksum="c39498071a042bb776a6a63a7aa55ef5498a730c" filename="jars/spim_data-2.2.5.jar"/>
    </plugin>
    <plugin filename="jars/j3dcore-1.6.0-scijava-3-SNAPSHOT.jar">
        <version checksum="7de3fb2dc16ff558cd10b9b7151a18f21c338639" timestamp="20200918173335" filesize="1955293">
            <description>3D Graphics API for the Java Platform</description>
            <dependency filename="jars/jogl-all.jar" timestamp="20151118124129"/>
            <dependency filename="jars/gluegen-rt.jar" timestamp="20151118124129"/>
            <author>Curtis Rueden</author>
        </version>
        <previous-version timestamp="20151123211031" timestamp-obsolete="20200731193402" checksum="a385a321a7e9a9ab0da67af020c6a6e3ebc4dd8b" filename="jars/j3dcore-1.6.0-scijava-2.jar"/>
        <previous-version timestamp="20200731193402" timestamp-obsolete="20200918173335" checksum="b6adb915151e67c1dc9a9eecc24dafbcc6ad6884" filename="jars/j3dcore-1.6.0-scijava-3-SNAPSHOT.jar"/>
    </plugin>
    <plugin filename="jars/commons-compress-1.18.jar">
        <previous-version timestamp="20160121045452" timestamp-obsolete="20200607222322" checksum="518ae46f82932aa18019c9887acfb413704e30b3" filename="jars/commons-compress-1.4.1.jar"/>
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="8bbe83390808b433895dbebf36669b8ce213e7af" filename="jars/commons-compress-1.18.jar"/>
    </plugin>
    <plugin filename="jars/bigdataviewer-vistools-1.0.0-beta-29.jar">
        <previous-version timestamp="20161211173104" timestamp-obsolete="0" checksum="95f179ad957f8c57c054f0fb2db501639e550632" filename="jars/bigdataviewer-vistools-1.0.0-beta-4.jar"/>
        <previous-version timestamp="20170530201750" timestamp-obsolete="0" checksum="afa3a35220983336227ee2611db9ce12b943f5c9" filename="jars/bigdataviewer-vistools-1.0.0-beta-5.jar"/>
        <previous-version timestamp="20171226155229" timestamp-obsolete="0" checksum="b01426ea3e467baf0094c975a3195ca9870b2db5" filename="jars/bigdataviewer-vistools-1.0.0-beta-8.jar"/>
        <previous-version timestamp="20180526000053" timestamp-obsolete="20190620124052" checksum="54721eef59228eeb6d6008aaea5ee02e3b2cc088" filename="jars/bigdataviewer-vistools-1.0.0-beta-11.jar"/>
        <previous-version timestamp="20190620124048" timestamp-obsolete="20200731193402" checksum="1fac0b34ee8cc50a642437fa05dadb8cab624c91" filename="jars/bigdataviewer-vistools-1.0.0-beta-15.jar"/>
        <previous-version timestamp="20200731193402" timestamp-obsolete="20210222164220" checksum="d677a35ccf59904acd39cbd82e17a65e40284271" filename="jars/bigdataviewer-vistools-1.0.0-beta-20.jar"/>
        <previous-version timestamp="20210222164216" timestamp-obsolete="20211112135002" checksum="164a852bae35849a42e5ff56aeab50ae1fff69ea" filename="jars/bigdataviewer-vistools-1.0.0-beta-29.jar"/>
        <previous-version timestamp="20211112135001" timestamp-obsolete="20220927132817" checksum="ddcbdcf5f2dd7acfe271539925a6210ce88857b6" filename="jars/bigdataviewer-vistools-1.0.0-beta-29.jar"/>
    </plugin>
    <plugin filename="jars/n5-imglib2-3.4.1.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="ad24eff8a08ff8ba3986aaf46e4dfefa7db00176" filename="jars/n5-imglib2-3.4.1.jar"/>
    </plugin>
    <plugin filename="jars/aws-java-sdk-s3-1.11.534.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="dc6901306cfe847be1404b2adf70368a881f47f7" filename="jars/aws-java-sdk-s3-1.11.534.jar"/>
    </plugin>
    <plugin filename="jars/n5-2.1.1.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="fd8424569df5e68c5bf40c01c9a0aca276faee02" filename="jars/n5-2.1.1.jar"/>
    </plugin>
    <plugin filename="jars/jackson-core-2.10.2.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="26e1990333a906f6b42e1136ba79b1187ed03747" filename="jars/jackson-core-2.10.2.jar"/>
    </plugin>
    <plugin filename="jars/aws-java-sdk-kms-1.11.534.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="8cb26ee79a47048b59f65b9ebcf060e1cc384e03" filename="jars/aws-java-sdk-kms-1.11.534.jar"/>
    </plugin>
    <plugin filename="jars/n5-aws-s3-2.1.1-platybrowser.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="4566cfb8aeff5e8c424cec1de7b5325307316b71" filename="jars/n5-aws-s3-2.1.1-platybrowser.jar"/>
    </plugin>
    <plugin filename="jars/lz4-java-1.5.0.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="c1046f79dfe6993026f3929c4eb298db2a674c28" filename="jars/lz4-java-1.5.0.jar"/>
    </plugin>
    <plugin filename="jars/jackson-databind-2.10.2.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="e4b7788a4c3bcfd05835dcd184a8c4199c482b7c" filename="jars/jackson-databind-2.10.2.jar"/>
    </plugin>
    <plugin filename="jars/jackson-annotations-2.10.2.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="1fd592e4cd9e541cad2085a0e567cec9e4b3803b" filename="jars/jackson-annotations-2.10.2.jar"/>
    </plugin>
    <plugin filename="jars/aws-java-sdk-core-1.11.534.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200915161818" checksum="a095bd961c757487e202882664bf3eff72554ac3" filename="jars/aws-java-sdk-core-1.11.534.jar"/>
    </plugin>
    <plugin filename="jars/flatlaf-1.0.jar">
        <previous-version timestamp="20211112135001" timestamp-obsolete="20220927132817" checksum="d389d2b44a60482f4d6251f15cc566b72abb925e" filename="jars/flatlaf-1.0.jar"/>
    </plugin>
    <plugin filename="jars/classgraph-4.8.60.jar">
        <version checksum="de775e7ff456f77d6fc7f3b57b8e6129f06f4f2c" timestamp="20221109160237" filesize="476777">
            <description>The uber-fast, ultra-lightweight classpath and module scanner for JVM languages.</description>
            <author>Luke Hutchison</author>
        </version>
    </plugin>
    <plugin filename="jars/bigvolumeviewer-0.3.4.jar">
        <previous-version timestamp="20211112135001" timestamp-obsolete="20230922102231" checksum="92acf189c05c878b491fe50af0704ca669ab199c" filename="jars/bigvolumeviewer-0.2.0.jar"/>
        <previous-version timestamp="20230922102231" timestamp-obsolete="20240607120434" checksum="1a14ce258d3ff9b75ddedb82eccb72f988bb8fdf" filename="jars/bigvolumeviewer-0.3.1.jar"/>
        <previous-version timestamp="20240607120434" timestamp-obsolete="20250124172633" checksum="fe0d35239a641f874c3c517a343029fc4872d11f" filename="jars/bigvolumeviewer-0.3.4.jar"/>
        <previous-version timestamp="20250124172633" timestamp-obsolete="20250416075330" checksum="2f0c36c0835b58a1959e0599a07f0519b3079936" filename="jars/bigvolumeviewer-0.3.4.jar"/>
    </plugin>
    <plugin filename="jars/mobie-0.6.1.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200618084927" checksum="6ed8ab00bc6b05e8ce17aa3e1e03e2e83091501c" filename="jars/mobie-0.5.0.jar"/>
        <previous-version timestamp="20200618084927" timestamp-obsolete="20200915161818" checksum="b82d01207683c0a093238d935383a532dfc259cd" filename="jars/mobie-0.5.0.jar"/>
        <previous-version timestamp="20200915161818" timestamp-obsolete="20200915162349" checksum="29a323aacf6891398dff5ba1bded6b9e92aab5a4" filename="jars/mobie-0.5.1-SNAPSHOT.jar"/>
        <previous-version timestamp="20200915162348" timestamp-obsolete="20200918173335" checksum="fcd616eb12fa530880af19295382159cac26852e" filename="jars/mobie-0.5.1-SNAPSHOT.jar"/>
        <previous-version timestamp="20200918173335" timestamp-obsolete="20201120123132" checksum="9e0b274ed0b3eb19a51f585e296285a4fce18428" filename="jars/mobie-0.5.1.jar"/>
        <previous-version timestamp="20201120123131" timestamp-obsolete="20210128103458" checksum="9f468f952268076b3f584b5be4c0177e493d7c45" filename="jars/mobie-0.5.3.jar"/>
        <previous-version timestamp="20210128103457" timestamp-obsolete="20210201113641" checksum="20f27197e0e6bbccf96e3cdf17b5c3f5d2d49103" filename="jars/mobie-0.5.5.jar"/>
        <previous-version timestamp="20210201113640" timestamp-obsolete="20210210172741" checksum="9792b3eef0a88322006d1a4477dd314edb17a80f" filename="jars/mobie-0.5.5.jar"/>
        <previous-version timestamp="20210210172741" timestamp-obsolete="20210211112003" checksum="29182aa0b64f8117816ca8db59c4d168279086bb" filename="jars/mobie-0.5.5.jar"/>
        <previous-version timestamp="20210211112002" timestamp-obsolete="20210211113606" checksum="37ad2028d985f534660bff0cffad49147051e38b" filename="jars/mobie-0.5.6.jar"/>
        <previous-version timestamp="20210211113606" timestamp-obsolete="20210312123443" checksum="28af199148f61756257f4ccc88ba66e69baa323f" filename="jars/mobie-0.5.6.jar"/>
        <previous-version timestamp="20210312123443" timestamp-obsolete="20211112135302" checksum="d1174a83870507499767401239c3edebfdd15e7e" filename="jars/mobie-0.6.1.jar"/>
    </plugin>
    <plugin filename="jars/imagej-utils-0.7.0.jar" executable="true">
        <previous-version timestamp="20200607222322" timestamp-obsolete="20200618084927" checksum="ad20537c81ed9f47028143796b2726d38778be42" filename="jars/imagej-utils-0.5.0.jar"/>
        <previous-version timestamp="20200618084927" timestamp-obsolete="20200915161818" checksum="bfac33038f4d1648c781fe2cbdeda1d0586f911e" filename="jars/imagej-utils-0.5.0.jar"/>
        <previous-version timestamp="20200915161818" timestamp-obsolete="20200918173335" checksum="7e020257e131340cab7810c538150745df7218f3" filename="jars/imagej-utils-0.5.4-SNAPSHOT.jar"/>
        <previous-version timestamp="20200918173335" timestamp-obsolete="20201120123132" checksum="6341c08374b8057424f4623d81aaff5a1a5bba86" filename="jars/imagej-utils-0.5.4.jar"/>
        <previous-version timestamp="20201120123131" timestamp-obsolete="20210128103458" checksum="111a2b7f6469ba16de3b61cb1412dd4599bbe7da" filename="jars/imagej-utils-0.5.6.jar"/>
        <previous-version timestamp="20210128103457" timestamp-obsolete="20210211112003" checksum="07796711f5f7cf9ead2ca0ba3a46de3f24c936af" filename="jars/imagej-utils-0.5.7.jar"/>
        <previous-version timestamp="20210211112002" timestamp-obsolete="20210211113606" checksum="e02c583882db9a1dd665f8f3e2642631ea9baad2" filename="jars/imagej-utils-0.5.8.jar"/>
        <previous-version timestamp="20210211113606" timestamp-obsolete="20210312123443" checksum="b110aaf0329d457c4a8245f298439aff42cfb42d" filename="jars/imagej-utils-0.5.8.jar"/>
        <previous-version timestamp="20210312123443" timestamp-obsolete="20211112135002" checksum="44d46332f4d6ca7c75d41548a206859a1d306242" filename="jars/imagej-utils-0.6.2.jar"/>
        <previous-version timestamp="20211112135001" timestamp-obsolete="20220525164640" checksum="533d0f95ae997e3f46e3a66beae68aa1b0f9e938" filename="jars/imagej-utils-0.6.4.jar"/>
        <previous-version timestamp="20220525164640" timestamp-obsolete="20220927132817" checksum="efccec362100109588405eb82d86ea9a6893fac7" filename="jars/imagej-utils-0.6.8.jar"/>
        <previous-version timestamp="20220927132816" timestamp-obsolete="20240607120434" checksum="47c6fab70b04d742090878dfcd003196f3b60a4e" filename="jars/imagej-utils-0.6.9.jar"/>
        <previous-version timestamp="20240607120434" timestamp-obsolete="20250124172633" checksum="89e3b7b827289d5d6efac40acffbad4302252a61" filename="jars/imagej-utils-0.7.0.jar"/>
    </plugin>
    <plugin filename="jars/mastodon-1.0.0-beta-21.jar">
        <previous-version timestamp="20211112135001" timestamp-obsolete="20230922102630" checksum="7035b792503db8ef6fe480c72c7836276c3d1711" filename="jars/mastodon-1.0.0-beta-21.jar"/>
    </plugin>
    <plugin filename="jars/mastodon-graph-1.0.0-beta-20.jar">
        <previous-version timestamp="20211112135001" timestamp-obsolete="20230922102630" checksum="4bb6915ef530d401d2965f4e3f3d78980f556fe0" filename="jars/mastodon-graph-1.0.0-beta-20.jar"/>
    </plugin>
    <plugin filename="jars/mobie-viewer-fiji-6.3.8.jar">
        <version checksum="a516ee79bacaa0a223efcc38eb04158ece614976" timestamp="20250804164857" filesize="1620781">
            <description>Fiji viewer for MoBIE projects</description>
            <dependency filename="jars/imglib2-realtransform.jar" timestamp="20210420104543"/>
            <dependency filename="jars/bigdataviewer-core.jar" timestamp="20210927120859"/>
            <dependency filename="jars/j3dcore.jar" timestamp="20200806131557"/>
            <dependency filename="jars/spim_data.jar" timestamp="20210913093606"/>
            <dependency filename="jars/bigdataviewer-playground.jar" timestamp="20211104092239"/>
            <dependency filename="jars/bigdataviewer-vistools.jar" timestamp="20210927120900"/>
            <dependency filename="jars/imglib2-cache.jar" timestamp="20210420124839"/>
            <dependency filename="jars/mobie-io.jar" timestamp="20211111141644"/>
            <dependency filename="jars/ij1-patcher.jar" timestamp="20210927120845"/>
            <dependency filename="jars/ij.jar" timestamp="20210927120857"/>
            <dependency filename="jars/scijava-listeners.jar" timestamp="20210420104749"/>
            <dependency filename="jars/gson.jar" timestamp="20210420104746"/>
            <dependency filename="jars/flatlaf.jar" timestamp="20210420124842"/>
            <dependency filename="jars/jdom2.jar" timestamp="20210420104746"/>
            <dependency filename="jars/jakarta.activation-api.jar" timestamp="20210420104822"/>
            <dependency filename="jars/commons-lang.jar" timestamp="20210420104603"/>
            <dependency filename="jars/commons-io.jar" timestamp="20210420104549"/>
            <dependency filename="jars/n5.jar" timestamp="20211112133628"/>
            <dependency filename="jars/imglib2-ij.jar" timestamp="20210420104543"/>
            <dependency filename="jars/scijava-optional.jar" timestamp="20210420104546"/>
            <dependency filename="jars/j3dutils.jar" timestamp="20210420104817"/>